pub const FRAME_RATE_HZ: usize = 30;
pub const AUDIO_SAMPLE_HZ: usize = 44_100;
pub const AUDIO_SAMPLE_BUFFER_SIZE: usize = 1024;
pub const AUDIO_SPECTRUM_PROPAGATE_HZ: usize = 5;

pub const AUDIO_SPECTRUM_INTERVAL_SAMPLES: usize = AUDIO_SAMPLE_HZ / FRAME_RATE_HZ;
pub const AUDIO_SPECTRUM_CYCLES: usize = FRAME_RATE_HZ / AUDIO_SPECTRUM_PROPAGATE_HZ;
